v3.9.12 Add: In -Set -Video Player. If Mpv isn't found, notification is given and the currently set video player is kept.
Add: Info added to home help: Start Autoplay from anywhere in the playlist. Then Resume Autoplay to start the
              last video that was playing on quit. More info located in View Playlist >>> Help

Removed: Features List in home help

diff --git a/videoinfox b/videoinfox
--- a/videoinfox
+++ b/videoinfox
@@ -1,14 +1,14 @@
 #!/bin/bash
 
-#  file : videoinfox v3.9.10								         
+#  file : videoinfox v3.9.12								         
 #  github and reddit: powerhousepro69
 #  GNU General Public License v2.0
 #  reddit:  /videoinfox
 
 # This is where Videoinfox's Version Number is set.
 
-ver="Videoinfox v3.9.10"  # Version Number: no blinking dot
-der=$(echo -e "Videoinfox v3\033[5m.\033m\033[0m\033[5m\033[5m\033[0m9.10")  # Version Number: with blinking dot
+ver="Videoinfox v3.9.12"  # Version Number: no blinking dot
+der=$(echo -e "Videoinfox v3\033[5m.\033m\033[0m\033[5m\033[5m\033[0m9.12")  # Version Number: with blinking dot
 
 
 ##################################################################################################################################################
@@ -1370,31 +1370,30 @@ echo "__________________________________________________________________________
 echo >> ~/.config/videoinfox/videoinfo.help
 echo " Create Unlimited Playlists." >>~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
-echo >> ~/.config/videoinfox/videoinfo.help
-echo " Playlist Add: Add videos to a playlist from the 3 below sources." >> ~/.config/videoinfox/videoinfo.help
+echo " Playlist Add: Add videos to a playlist from the 4 below sources." >> ~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
 echo " - Home Screen. Add videos from recursive search results or recursive directory listings to the Playlist." >>~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
 echo " - Navigate Tree. Add videos from one level deep directory listings to the Playlist." >>~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
-echo " - Navigate Tree >>> Show All - Directory To Playlist. Add all videos in the current directory to a new Playlist." >>~/.config/videoinfox/videoinfo.help
+echo " - Directory To Playlist in Navigate Tree >>> Show All. Add all videos in the current directory to a new Playlist." >>~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
 echo " - Played List. Add videos from Played List to the Playlist." >>~/.config/videoinfox/videoinfo.help
-echo >> ~/.config/videoinfox/videoinfo.help
 echo "                Play Clipboard, Last Download and Play Line all write to the Played List." >>~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
 echo "                Note: One exception. Play Line in View Playlist never writes to the Played List." >>~/.config/videoinfox/videoinfo.help
+echo >> ~/.config/videoinfox/videoinfo.help
+echo " Start Autoplay from anywhere in the playlist. Then Resume Autoplay to start the last video that was playing" >>~/.config/videoinfox/videoinfo.help
+echo " on quit. More info located in View Playlist >>> Help" >>~/.config/videoinfox/videoinfo.help
 echo "___________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
 echo " Navigate Tree: Whatever the directory is when entering Navigate Tree will be set as the Treetop." >> ~/.config/videoinfox/videoinfo.help
 echo "                Recursive Navigation from the Treetop." >> ~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
-echo >> ~/.config/videoinfox/videoinfo.help
 echo "                While in Navigate Tree, there are two ways to change the Treetop." >> ~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
 echo "                - Default Dirs" >> ~/.config/videoinfox/videoinfo.help
 echo "                - Change Treetop" >> ~/.config/videoinfox/videoinfo.help
-echo >> ~/.config/videoinfox/videoinfo.help
 echo "___________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
 echo " videoinfox -h to see command line options." >> ~/.config/videoinfox/videoinfo.help
@@ -1402,66 +1401,10 @@ echo "__________________________________________________________________________
 echo >> ~/.config/videoinfox/videoinfo.help
 echo " When you use:  Videoinfox Update in Settings (Set), the update will always be applied to: /usr/local/bin" >> ~/.config/videoinfox/videoinfo.help
 echo "___________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo.help
-echo "___________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
-echo "  Play Clipboard voodoo wouldn't have been possible without XCLIP" >> ~/.config/videoinfox/videoinfo.help
+echo " Play Clipboard wouldn't have been possible without XCLIP" >> ~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
-echo "  Download feature wouldn't have been possible without YT-DLP" >> ~/.config/videoinfox/videoinfo.help
-echo >> ~/.config/videoinfox/videoinfo.help
-echo >> ~/.config/videoinfox/videoinfo.help
-echo "  Videoinfox Features:" >> ~/.config/videoinfox/videoinfo.help
-echo >> ~/.config/videoinfox/videoinfo.help
-echo "  - Navigation was designed to be robust and efficient. One keypress for all menu selections." >> ~/.config/videoinfox/videoinfo.help 
-echo "  - Check for update on startup and notifity if update is available. Download and update in Videoinfox." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Play a local file by entering the line number. Play single video or autoplay the entire list." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Create unlimited Playlists from: Recusive search results, Recursive directory listings and the Played List" >> ~/.config/videoinfox/videoinfo.help
-echo "  - Play Clipboard: Blinking notification when there is a valid video url for play." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Play Clipboard: Download a video url that is in the clipboard via Yt-dlp and autoplay." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Play Clipboard is available in: Home  Played List  Play List  Yt-dlp Menu  View Downloads" >> ~/.config/videoinfox/videoinfo.help
-echo "  - See codec, resolution and duration on the playing video." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Play Directory autoplay available in: Home Screen, Navigate Tree and View Downloads." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Autoplay video files in the current directory with option to quit. videoinfox -d" >> ~/.config/videoinfox/videoinfo.help
-echo "  - Blinking Play Directory otification when there are video files in the current directory." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Navigate Tree Blinking Change Directory notification when there is a valid directory in the clipboard." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Navigate Tree with Play Directory autoplay and Play Line with autoplay. Select line number to start play." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Video Player (ffplay) auto closes when the video ends." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Auto clear the clipboard after the video player is closed." >> ~/.config/videoinfox/videoinfo.help
-echo "  - To watch the last download after Play Clipboard cleared the link select Last Download." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Auto clear the clipboard of invalid files and urls." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Press enter after your copy to the clipboard to validate clipboard content." >> ~/.config/videoinfox/videoinfo.help
-echo "  - File types searched for: .webm   .mp4   .mkv   .avi   .divx" >> ~/.config/videoinfox/videoinfo.help
-echo "  - Rapid directory changing by setting default directories (4) in Settings. The 5th is dir at last exit." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Default Dirs - 1 2 3 4 5  available in: Home  Navigate Tree  Download List  More Options" >> ~/.config/videoinfox/videoinfo.help
-echo "  - Play Line option. Only play the line number entered and write to Played List." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Autoplay Line option. Start autoplay from any line in the Played List by entering the line number." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Played List will keep track of everything played except for Play Directory and Autoplay Line." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Played List: Play All option that will auto play the entire list with option to quit." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Playlist: Save a list of videos from search results, directory listings and Played List." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Remove duplicates from the Playlist and Played List." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Enter a video file with full path to get info on and play." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Auto save last find result(s) and autoload until deleted. Defaulted to never save. Change in Settings." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Yt-dlp integration for easy download and play of single url's or entire lists." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Download Queue: Add unlimited Videoinfox User Download Lists to the queue for download." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Download Default: Yt-dlp with no arguments. Download only. No auto play." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Download Choose: Choose video type and quality before download. Download only. No auto play." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Self Destruct: Download, auto play, delete when the player is closed." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Last Download available in: Home and Yt-dlp Menu for: Play Clipboard, Download Default and Download Choose." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Download List: Blinking notification on list load." >> ~/.config/videoinfox/videoinfo.help
-echo "  - View Logs: Blinking notification on log load." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Default List: Keep pasting Video URL's on the fly from the clipboard to the Default List." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Default List companion: Create a gui shortcut for: videoinfox -a  to add to the Default List." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Unlimited User Lists: Keep pasting Video URL's on the fly from the clipboard to the User Set List." >> ~/.config/videoinfox/videoinfo.help
-echo "  - User Set List companion: Create a gui shortcut for: videoinfox -l  to add to the User Set list." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Download any list. Any name and location. No need to use the Videoinfox interface: videoinfox -u listname" >> ~/.config/videoinfox/videoinfo.help
-echo "  - Download and update Yt-dlp in Videoinfox." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Save directory state on exit to load on next run." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Change directory by entering full path." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Find directory and change to it by copying it to clipboard." >> ~/.config/videoinfox/videoinfo.help
-echo "  - List video info one directory deep. Save per directory." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Recursive count of videos broken down by video type." >> ~/.config/videoinfox/videoinfo.help
-echo "  - Recursive duration (days:hrs:min:sec) Save per directory." >> ~/.config/videoinfox/videoinfo.help
-echo "  - GUI notifications." >> ~/.config/videoinfox/videoinfo.help
-echo "___________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo.help
+echo " Download feature wouldn't have been possible without YT-DLP" >> ~/.config/videoinfox/videoinfo.help
 echo "___________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
 echo " Privacy Policy: Videoinfox will never collect or attempt to transmit any information on it's users." >> ~/.config/videoinfox/videoinfo.help
@@ -1516,6 +1459,14 @@ echo >> ~/.config/videoinfox/videoinfo-ver-history
 
 
 
+echo " _________________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo-ver-history
+echo >> ~/.config/videoinfox/videoinfo-ver-history
+echo " v3.9.12 Add: In -Set -Video Player. If Mpv isn't found, notification is given and the currently set video player is kept." >> ~/.config/videoinfox/videoinfo-ver-history
+echo >> ~/.config/videoinfox/videoinfo-ver-history
+echo "         Add: Info added to home help: Start Autoplay from anywhere in the playlist. Then Resume Autoplay to start the" >> ~/.config/videoinfox/videoinfo-ver-history
+echo "              last video that was playing on quit. More info located in View Playlist >>> Help" >> ~/.config/videoinfox/videoinfo-ver-history
+echo >> ~/.config/videoinfox/videoinfo-ver-history
+echo "         Removed: Features List in home help" >> ~/.config/videoinfox/videoinfo-ver-history
 echo " _________________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo-ver-history
 echo >> ~/.config/videoinfox/videoinfo-ver-history
 echo " v3.9.10 Add: Watch videos with (default) ffplay, mpv or any video player. Home Screen: -Set -Video Player" >> ~/.config/videoinfox/videoinfo-ver-history
@@ -4482,7 +4433,8 @@ read -r -n1 optionv
         echo
         echo " Everytime Start Autoplay is used, it will write a new file for Resume Autoplay."
         echo " Run Start Autoplay first. Then use Resume Autoplay to continue watching where you left off."
-        echo " Resume Autoplay will start with the last video that was playing when the play loop was quit."
+        echo " Resume Autoplay will start with the last video that was playing when Start Autoplay was quit."
+        echo " Resume Autoplay will also keep track of the last video that was playing when quit."
         echo " When Resume Autoplay reaches the end of the playlist, it will remain there until Start Autoplay is run again."
         echo
         echo " Note: If the playlist is changed with Playlist Add or Remove Line after running Start Autoplay,"
@@ -6847,7 +6799,8 @@ read -r -n1 optionv
         echo
         echo " Everytime Start Autoplay is used, it will write a new file for Resume Autoplay."
         echo " Run Start Autoplay first. Then use Resume Autoplay to continue watching where you left off."
-        echo " Resume Autoplay will start with the last video that was playing when the play loop was quit."
+        echo " Resume Autoplay will start with the last video that was playing when Start Autoplay was quit."
+        echo " Resume Autoplay will also keep track of the last video that was playing when quit."
         echo " When Resume Autoplay reaches the end of the playlist, it will remain there until Start Autoplay is run again."
         echo
         echo " Note: If the playlist is changed with Playlist Add or Remove Line after running Start Autoplay,"
@@ -8331,7 +8284,8 @@ read -r -n1 optionv
         echo
         echo " Everytime Start Autoplay is used, it will write a new file for Resume Autoplay."
         echo " Run Start Autoplay first. Then use Resume Autoplay to continue watching where you left off."
-        echo " Resume Autoplay will start with the last video that was playing when the play loop was quit."
+        echo " Resume Autoplay will start with the last video that was playing when Start Autoplay was quit."
+        echo " Resume Autoplay will also keep track of the last video that was playing when quit."
         echo " When Resume Autoplay reaches the end of the playlist, it will remain there until Start Autoplay is run again."
         echo
         echo " Note: If the playlist is changed with Playlist Add or Remove Line after running Start Autoplay,"
@@ -9467,7 +9421,6 @@ case $optionsettings in
          break;;
   
          1)
-         
          echo "1" > ~/.config/videoinfox/videoinfox.video-player
          echo
          echo " ffplay set . . ."
@@ -9475,11 +9428,18 @@ case $optionsettings in
          ;;
 
 
-         2)
-         echo "2" > ~/.config/videoinfox/videoinfox.video-player
-         echo
-         echo " mpv set . . . "
-         sleep 1.7
+         2)         
+         if ! command -v mpv &> /dev/null ####### Check for: mpv and set if installed ########
+           then
+               echo
+               echo " mpv not found . . ."
+               sleep 1.7
+           else
+               echo "2" > ~/.config/videoinfox/videoinfox.video-player
+               echo
+               echo " mpv set . . . "
+               sleep 1.7
+         fi
          ;;
 
         
