v5.9.53 Add: -Stream added to Browse in Download Channel. Stream selected video in default browser.

diff --git a/videoinfox b/videoinfox
--- a/videoinfox
+++ b/videoinfox
@@ -5,10 +5,10 @@
 #  GNU General Public License v2.0
 #  reddit:  /videoinfox
 
-ver="Videoinfox v5.9.52"  # Version Number: no blinking dot
-ver2=$(echo -e "\e[3mVideoinfox v5.9.52\e[0m")
-der=$(echo -e "\e[3mVideoinfox v5\033[5m.\033m\033[0m\033[5m\033[5m\033[0m\e[3m9.52\033[0m") # Version Number: with blinking dot
-vn="v5.9.52" #V! update help files on update. disabled until fixed. all help files are written on every run.
+ver="Videoinfox v5.9.53"  # Version Number: no blinking dot
+ver2=$(echo -e "\e[3mVideoinfox v5.9.53\e[0m")
+der=$(echo -e "\e[3mVideoinfox v5\033[5m.\033m\033[0m\033[5m\033[5m\033[0m\e[3m9.53\033[0m") # Version Number: with blinking dot
+vn="v5.9.53" #V! update help files on update. disabled until fixed. all help files are written on every run.
 
 ##################################################################################################################################################
 #  DEPENDENCIES REQUIRED:  #######################################################################################################################
@@ -1304,7 +1304,7 @@ fi
 ##################################################################################################################################################
 echo "_________________________________________________________________________________________________________________" > ~/.config/videoinfox/d-ch-help
 echo >> ~/.config/videoinfox/d-ch-help
-echo " Videoinfox v.5.9.52 >>> DOWNLOAD CHANNEL >>> HELP" >> ~/.config/videoinfox/d-ch-help
+echo " Videoinfox v.5.9.53 >>> DOWNLOAD CHANNEL >>> HELP" >> ~/.config/videoinfox/d-ch-help
 echo >> ~/.config/videoinfox/d-ch-help
 echo " Arrows - up/dwn                                                                                        q - Quit" >> ~/.config/videoinfox/d-ch-help
 echo "_________________________________________________________________________________________________________________" >> ~/.config/videoinfox/d-ch-help
@@ -1375,7 +1375,7 @@ echo "__________________________________________________________________________
 echo >> ~/.config/videoinfox/videoinfox.download-list-help
 
 #V!VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
-echo " Videoinfox v5.9.52   Where video download and play is a clipboard copy away . . ." >> ~/.config/videoinfox/videoinfox.download-list-help
+echo " Videoinfox v5.9.53   Where video download and play is a clipboard copy away . . ." >> ~/.config/videoinfox/videoinfox.download-list-help
 echo "___________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfox.download-list-help
 echo "___________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfox.download-list-help
 echo >> ~/.config/videoinfox/videoinfox.download-list-help
@@ -1527,7 +1527,7 @@ echo >> ~/.config/videoinfox/videoinfox.download-list-help
 echo "___________________________________________________________________________________________________________________" > ~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
 #V!VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
-echo " Videoinfox v5.9.52   Where video download and play is a clipboard copy away . . ." >> ~/.config/videoinfox/videoinfo.help
+echo " Videoinfox v5.9.53   Where video download and play is a clipboard copy away . . ." >> ~/.config/videoinfox/videoinfo.help
 echo "___________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo.help
 echo >> ~/.config/videoinfox/videoinfo.help
 echo " VIDEOINFOX WILL NOT EDIT VIDEO FILES. IT IS A FRONT-END TO PLAY VIDEOS AND DOWNLOAD VIDEOS." >> ~/.config/videoinfox/videoinfo.help
@@ -1886,7 +1886,7 @@ echo " q - quit                                                                 
 echo " _________________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo-ver-history
 echo >> ~/.config/videoinfox/videoinfo-ver-history
 #V!
-echo " 241 Version Updates" >> ~/.config/videoinfox/videoinfo-ver-history
+echo " 242 Version Updates" >> ~/.config/videoinfox/videoinfo-ver-history
 echo " _________________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo-ver-history
 echo >> ~/.config/videoinfox/videoinfo-ver-history
 echo " There are 4 items on the Videoinfox development road map." >> ~/.config/videoinfox/videoinfo-ver-history
@@ -1909,6 +1909,9 @@ echo " _________________________________________________________________________
 #echo " _________________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo-ver-history
 
 #V!VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
+echo >> ~/.config/videoinfox/videoinfo-ver-history
+echo " v5.9.53 Add: -Stream added to Browse in Download Channel. Stream selected video in default browser." >> ~/.config/videoinfox/videoinfo-ver-history
+echo " _________________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo-ver-history
 echo >> ~/.config/videoinfox/videoinfo-ver-history
 echo " v5.9.52 Fix: Create empty options file for yt-dlp if it doesn't exist." >> ~/.config/videoinfox/videoinfo-ver-history
 echo " _________________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo-ver-history
@@ -2135,15 +2138,10 @@ echo " v5.5.19 Add: Line number added to Resume: in -View Playlist" >> ~/.config
 echo >> ~/.config/videoinfox/videoinfo-ver-history
 echo "         Add: Line number added to Resume: in -Play Queue" >> ~/.config/videoinfox/videoinfo-ver-history
 echo " _________________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo-ver-history
+
+#V!####################### Here for v5.9.53 but up next on the chopping block with the next update #######################
 echo >> ~/.config/videoinfox/videoinfo-ver-history
 echo " v5.5.17 Edit: Home Help. Find your videos fast. Powerful playlist building and editing..... section" >> ~/.config/videoinfox/videoinfo-ver-history
-echo " _________________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo-ver-history
-
-#V!####################### Here for v5.9.52 but up next on the chopping block with the next update #######################
-echo >> ~/.config/videoinfox/videoinfo-ver-history
-echo " v5.5.16 Change: Moved option -Clrclp below -Play Clipboard in -Played List" >> ~/.config/videoinfox/videoinfo-ver-history
-echo >> ~/.config/videoinfox/videoinfo-ver-history
-echo "         Fix: Had to add 3gp files to -Play Clipboard filter." >> ~/.config/videoinfox/videoinfo-ver-history
 echo " _________________________________________________________________________________________________________________________" >> ~/.config/videoinfox/videoinfo-ver-history
 ####################################################################################################################
 
@@ -20830,7 +20828,7 @@ echo
 echo " ""$der"" >>> YT-DLP MENU >>> DOWNLOAD CHANNEL >>> BROWSE"
 echo "___________________________________________________________________________________________________________________"
 echo
-echo " t - Search            a - Add to Queue     d - Download     n - Not Downloaded                           q - Quit"
+echo " t - Search            a - Add to Queue     d - Download     n - Not Downloaded     s - Stream            q - Quit"
 echo " c - Clear Results     b - All to Queue     z - Queue        y - Downloaded                               u - Set"
 echo
 echo -en " Enter Option: "
@@ -20899,6 +20897,125 @@ sed 's/[^ ]* //' ~/.config/videoinfox/tmp/search-url-playlist.tmp2 > ~/.config/v
 
 fi
 fi
+fi
+;;
+
+
+s) # @STREAM VIDEO FROM PLAYLIST
+if [[ "$viewset" = 1 ]] # entire list
+then
+clear
+linecount=$(sed -n '$=' ~/.config/videoinfox/tmp/download-browse-odd) # line count
+cat ~/.config/videoinfox/tmp/download-browse-odd-numbered
+echo
+read -r -p "Stream Video: " linenumber  # waiting fot user input
+
+if [ -z "$linenumber" ]
+then # BLANK ENTRY
+    :
+else
+
+re='^[0-9]+$'
+if ! [[ $linenumber =~ $re ]]
+  then
+      :
+  else
+
+if [ "$linenumber" = 0 ]
+  then
+      :
+  else
+
+if ! [[ "$linenumber" -eq "$linenumber" ]]
+  then
+      :
+  else
+      if [[ $linenumber -gt $linecount ]]
+        then  # ENTRY EXCEEDS TOTAL NUMBER OF LINES
+            :
+else
+clear
+
+if [ -z "$urlfind" ]
+then
+clear
+echo
+echo " Url is missing to stream a single video from the following domain:"
+echo " ""$baseurl"
+echo
+echo " An entry can be created in -Set"
+echo
+read -r -p " Press enter to continue . . ."
+
+else
+videoid=$(sed -n "$linenumber"p ~/.config/videoinfox/tmp/download-browse-even)
+eval xdg-open http://"$urlfind""$videoid"
+
+fi
+fi
+fi
+fi
+fi
+fi
+#;;
+
+elif [[ "$viewset" = 2 ]] # search results
+then
+clear
+linecount=$(sed -n '$=' ~/.config/videoinfox/tmp/search-url-playlist-odd) # line count
+cat ~/.config/videoinfox/tmp/search-url-playlist.tmp-numbered
+echo
+read -r -p "Stream Video: " linenumber  # waiting fot user input
+
+if [ -z "$linenumber" ]
+then # BLANK ENTRY
+    :
+else
+
+re='^[0-9]+$'
+if ! [[ $linenumber =~ $re ]]
+  then
+      :
+  else
+
+if [ "$linenumber" = 0 ]
+  then
+      :
+  else
+
+if ! [[ "$linenumber" -eq "$linenumber" ]]
+  then
+      :
+  else
+      if [[ $linenumber -gt $linecount ]]
+        then  # ENTRY EXCEEDS TOTAL NUMBER OF LINES
+            :
+else
+clear
+
+if [ -z "$urlfind" ]
+then
+clear
+echo
+echo " Url is missing to stream a single video from the following domain:"
+echo " ""$baseurl"
+echo
+echo " An entry can be created in -Set"
+echo
+read -r -p " Press enter to continue . . ."
+
+else
+idsearch=$(sed -n "$linenumber"p ~/.config/videoinfox/tmp/search-url-playlist-even)
+videoid=$(sed -n "$idsearch"p ~/.config/videoinfox/tmp/download-browse-even)
+eval xdg-open http://"$urlfind""$videoid"
+
+fi
+fi
+fi
+fi
+fi
+fi
+
 fi
 ;;
 
@@ -21965,7 +22082,7 @@ if [ -z "$urlfind" ]
 then
 clear
 echo
-echo " Url is missing to download a single videos from the following domain:"
+echo " Url is missing to download a single video from the following domain:"
 echo " ""$baseurl"
 echo
 echo " An entry can be created in -Set"
@@ -22033,7 +22150,7 @@ if [ -z "$urlfind" ]
 then
 clear
 echo
-echo " Url is missing to download a single videos from the following domain:"
+echo " Url is missing to download a single video from the following domain:"
 echo " ""$baseurl"
 echo
 echo " An entry can be created in -Set"
